# Generated by Django 4.0.4 on 2022-05-25 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samochody', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=20)),
                ('miasto', models.CharField(max_length=20)),
                ('adres', models.CharField(max_length=20)),
                ('ulica_nr', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Historia_serwisu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(default=0)),
                ('kwota', models.IntegerField(default=0)),
            ],
        ),
    ]
