# Generated by Django 4.0.4 on 2022-05-25 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('samochody', '0004_rename_service_history_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealer',
            name='marka',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='samochody.car'),
        ),
        migrations.AddField(
            model_name='service',
            name='nazwa',
            field=models.ManyToManyField(to='samochody.dealer'),
        ),
    ]
